/*
 Navicat MySQL Data Transfer

 Source Server         : local-xampp
 Source Server Type    : MySQL
 Source Server Version : 100428
 Source Host           : localhost:3306
 Source Schema         : snw_orarend

 Target Server Type    : MySQL
 Target Server Version : 100428
 File Encoding         : 65001

 Date: 23/09/2024 20:20:17
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for targyak
-- ----------------------------
DROP TABLE IF EXISTS `targyak`;
CREATE TABLE `targyak` (
  `ttrov` varchar(12) NOT NULL,
  `ttnev` varchar(100) NOT NULL,
  PRIMARY KEY (`ttrov`),
  KEY `ttnev` (`ttnev`),
  KEY `ttrov` (`ttrov`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_hungarian_ci ROW_FORMAT=COMPACT;

-- ----------------------------
-- Records of targyak
-- ----------------------------
BEGIN;
INSERT INTO `targyak` VALUES (';Acsgyak', ';Ács gyakorlat');
INSERT INTO `targyak` VALUES (';Asztgyak', ';Asztalos gyakorlat');
INSERT INTO `targyak` VALUES (';Autsz.gyak', ';Autoszerelő gyakorlat');
INSERT INTO `targyak` VALUES (';Burkgyak', ';Burkoló gyakorlat');
INSERT INTO `targyak` VALUES (';CSGY', ';Csoportos gyakorlat');
INSERT INTO `targyak` VALUES (';Ertgy', ';Értékesítési gyakorlat');
INSERT INTO `targyak` VALUES (';Festgyak', ';Festő gyakorlat');
INSERT INTO `targyak` VALUES (';H+Szgyak', ';H+Szgyak');
INSERT INTO `targyak` VALUES (';H+Vgyak', ';Himző és varró gyakorlat');
INSERT INTO `targyak` VALUES (';Hgyak', ';Himző gyakorlat');
INSERT INTO `targyak` VALUES (';Komgyak', ';Kőműves gyakorlat');
INSERT INTO `targyak` VALUES (';Szgyak', ';Szgyak');
INSERT INTO `targyak` VALUES (';Vgyak', ';Varró gyakorlat');
INSERT INTO `targyak` VALUES (';Villgyak', ';Villanyszerelő gyakorlat');
INSERT INTO `targyak` VALUES ('Bsk', '*A beteg szükségleteinek kielégítése');
INSERT INTO `targyak` VALUES ('Bmfi', '*A betegs. tünetei és a betegmegf. szempont.');
INSERT INTO `targyak` VALUES ('Bemb', '*A bőr és az érzékszervek megbetegedései');
INSERT INTO `targyak` VALUES ('Cskbf', '*A csecsemő és kisgyermek beszédfejlődése');
INSERT INTO `targyak` VALUES ('Cskmf', '*A csecsemő és kisgyermek mozgásfejlődése');
INSERT INTO `targyak` VALUES ('Goad', '*A gondozás adminisztrációja');
INSERT INTO `targyak` VALUES ('Goszf', '*A gondozási szükségletek felmérése');
INSERT INTO `targyak` VALUES ('.Goatt', '*A gondozó attitüdje, képességek, készségek menth. elméletigényes gyak.');
INSERT INTO `targyak` VALUES ('Gdok', '*A gondozó- nevelő munka szakmai dokumentálásaintézmény és demons');
INSERT INTO `targyak` VALUES ('Gybf', '*A gyermek biológiai fejlődése');
INSERT INTO `targyak` VALUES ('Gyeki', '*A gyermek ellátásával kapcsolatos ismeretek');
INSERT INTO `targyak` VALUES ('Gyfkd', '*A gyermek fejlődésével kapcsolatos dokumentáció');
INSERT INTO `targyak` VALUES ('Gyjt', '*A gyermek játéktevékenysége');
INSERT INTO `targyak` VALUES ('Gymi', '*A gyermek megfigyelése intézményi heti 1X');
INSERT INTO `targyak` VALUES ('Gytf', '*A gyermek testi fejlődése');
INSERT INTO `targyak` VALUES ('Gyvz', '*A gyermek viselkedésének zavarai');
INSERT INTO `targyak` VALUES ('Gylf', '*A gyermek, lelki, szociális fejlődése');
INSERT INTO `targyak` VALUES ('Gymu', '*A gyermekcsoport működése');
INSERT INTO `targyak` VALUES ('Gyfd', '*A gyermekfelügyelet dokumentációja');
INSERT INTO `targyak` VALUES ('Gyomu', '*A gyermekotthon működése');
INSERT INTO `targyak` VALUES ('Gyesz', '*A gyermekotthoni élet szervezése');
INSERT INTO `targyak` VALUES ('Gysbh', '*A gyógyászati segédeszközök beszerzése és használata');
INSERT INTO `targyak` VALUES ('Gybhg', '*A gyógyíthatatlan betegek és a haldoklók gondozása');
INSERT INTO `targyak` VALUES ('Hgf', '*A három év alatti gyermek gondozási feladatai');
INSERT INTO `targyak` VALUES ('Higypd', '*A házi időszakos gyermekellátás pszichológiai dimenziói');
INSERT INTO `targyak` VALUES ('Hok', '*A helyi önkormányzatok költségvetése');
INSERT INTO `targyak` VALUES ('Jejk', '*A jóléti ellátások jogi keretei');
INSERT INTO `targyak` VALUES ('Jegy', '*A jóléti ellátások jogi keretei, gyermvéd j.');
INSERT INTO `targyak` VALUES ('Kvrb', '*A keringési- és a vérképző rendszer betegségei');
INSERT INTO `targyak` VALUES ('Katk', '*A kisgyermek aktív tevékenysége és a környezet');
INSERT INTO `targyak` VALUES ('Kek', '*A kisgyermek egészsége, közegésségügy');
INSERT INTO `targyak` VALUES ('Kgd', '*A kisgyermek gondozási gyakorlat/  demons. ');
INSERT INTO `targyak` VALUES ('Kgi', '*A kisgyermek gondozási gyakorlat/intézményi.');
INSERT INTO `targyak` VALUES ('Kgyhiv', '*A kisgyermek gondozó- nevelő, mint hivatás / szocializáció folyamata');
INSERT INTO `targyak` VALUES ('Kgyszf', '*A kisgyermek személyiségének fejlődése');
INSERT INTO `targyak` VALUES ('Kgyt', '*A kisgyermek táplálása');
INSERT INTO `targyak` VALUES ('Kne', '*A kisgyermekgondozás és nevelés egysége');
INSERT INTO `targyak` VALUES ('Kped', '*A kisgyermekkor pedagógiája');
INSERT INTO `targyak` VALUES ('Lb', '*A légzőrendszer betegségei');
INSERT INTO `targyak` VALUES ('Mmtsz', '*A mai magyar társadalom szerkezete');
INSERT INTO `targyak` VALUES ('Mvsz', '*A munkát vállaló szülő és a gyermek');
INSERT INTO `targyak` VALUES ('Nkesz', '*A napközbeni ellátás, mint szolgáltatás');
INSERT INTO `targyak` VALUES ('Naszg', '*A nem állami szervek gazdálkodása');
INSERT INTO `targyak` VALUES ('Szgd', '*A személyes gondoskodás dilemmái');
INSERT INTO `targyak` VALUES ('Szggy', '*A személyes gondoskodás gyakorlata');
INSERT INTO `targyak` VALUES ('Szmka', '*A szervezet működését károsító állapotok');
INSERT INTO `targyak` VALUES ('Szet', '*A szociális ellátás tervezése');
INSERT INTO `targyak` VALUES ('Szem', '*A szociális ellátások marketingje');
INSERT INTO `targyak` VALUES ('Szgad', '*A szociális gond, szerv adminisztrációs gyak');
INSERT INTO `targyak` VALUES ('Szig', '*A szociális intézmények gazdálkodásának gyakorlata');
INSERT INTO `targyak` VALUES ('Szadm', '*A szociális szolgáltatások adminisztrációjának ismeretei');
INSERT INTO `targyak` VALUES ('Szfin', '*A szociális szolgáltatások finanszírozási formái');
INSERT INTO `targyak` VALUES ('Szf', '*A szocializáció folyamata');
INSERT INTO `targyak` VALUES ('Szuf', '*A szükségletfelmérés gyakorlata');
INSERT INTO `targyak` VALUES ('Veal', '*A vezetés alapjai');
INSERT INTO `targyak` VALUES ('.Adm', '*Adminisztrációs gyakorlat intézményi heti 1X');
INSERT INTO `targyak` VALUES ('Akfo', '*Aktivitás és foglalkozás');
INSERT INTO `targyak` VALUES ('Aáf', '*Alapápolási feladatok');
INSERT INTO `targyak` VALUES ('.Aa', '*Alapápolási gyakorlat');
INSERT INTO `targyak` VALUES ('Abel', '*Alapápolási gyakorlat a belgyógyászaton');
INSERT INTO `targyak` VALUES ('Aseb', '*Alapápolási gyakorlat a sebészeten');
INSERT INTO `targyak` VALUES ('Aapi', '*Alapápolási ismeretek');
INSERT INTO `targyak` VALUES ('Arj', '*Általános és részletes járványtan');
INSERT INTO `targyak` VALUES ('Ark', '*Általános és részletes kórtan');
INSERT INTO `targyak` VALUES ('Anel', '*Anatómia-élettan');
INSERT INTO `targyak` VALUES ('Aeb', '*Ápolás elmélete - betegbiztonság');
INSERT INTO `targyak` VALUES ('Aeko', '*Ápolás elmélete, kockázatai');
INSERT INTO `targyak` VALUES ('Aeku', '*Ápolás elmélete,kutatása');
INSERT INTO `targyak` VALUES ('Aeti', '*Ápolás etika');
INSERT INTO `targyak` VALUES ('Agy', '*Ápolás gyakorlata');
INSERT INTO `targyak` VALUES ('Atu', '*Ápolás tudomány');
INSERT INTO `targyak` VALUES ('Aako', '*Ápolási asszisztens kompetenciája ');
INSERT INTO `targyak` VALUES ('Aafe', '*Ápolási asszisztensi feladatok');
INSERT INTO `targyak` VALUES ('Apf', '*Ápolási feladatok');
INSERT INTO `targyak` VALUES ('Apfe', '*Ápolási feladatok elm.');
INSERT INTO `targyak` VALUES ('.Apf', '*Ápolási feladatok gyak.');
INSERT INTO `targyak` VALUES ('Agi', '*Ápolási gondozási intézményben');
INSERT INTO `targyak` VALUES ('Api', '*Ápolási ismeretek');
INSERT INTO `targyak` VALUES ('Apie', '*Ápolási ismeretek elm.');
INSERT INTO `targyak` VALUES ('.Api', '*Ápolási ismeretek gyak.');
INSERT INTO `targyak` VALUES ('Aszf', '*Ápolási szükségletek felmérése');
INSERT INTO `targyak` VALUES ('Atgy', '*Ápolási terápiás gyakorlatok');
INSERT INTO `targyak` VALUES ('Ati', '*Ápolási terápiás ismeretek');
INSERT INTO `targyak` VALUES ('Avei', '*Ápolási vizsgálatok - előkészületek ismeretei');
INSERT INTO `targyak` VALUES ('Avegy', '*Ápolási vizsgálatok -előkészületek gyakorlata');
INSERT INTO `targyak` VALUES ('Adf', '*Ápolói diagnosztikai feladatok, beteg és eszköz előkészítés elm.');
INSERT INTO `targyak` VALUES ('.Apd', '*Ápolói diagnosztikai feladatok, beteg és eszköz előkészítés gyak.');
INSERT INTO `targyak` VALUES ('Atie', '*Ápolói terápiák ismerete elm.');
INSERT INTO `targyak` VALUES ('Atigy', '*Ápolói terápiák ismerete gyak.');
INSERT INTO `targyak` VALUES ('Adea', '*Az adminisztráció elméleti alapjai');
INSERT INTO `targyak` VALUES ('Apad', '*Az ápolás adminisztrációja');
INSERT INTO `targyak` VALUES ('Evdok', '*Az egészségvédelem dokumentációja');
INSERT INTO `targyak` VALUES ('Ecsm', '*Az egyéni és családsegítő munka gyakorlata');
INSERT INTO `targyak` VALUES ('Eecs', '*Az egyéni esetkezelés és a családsegítés gyakorlata');
INSERT INTO `targyak` VALUES ('Eszj', '*Az egyes szolgáltatások jellemzői');
INSERT INTO `targyak` VALUES ('Eszf', '*Az ellátási szükségletek felmérésének gyakorlata számítógépes teremben');
INSERT INTO `targyak` VALUES ('Etfm', '*Az emberi test felépítése és működése');
INSERT INTO `targyak` VALUES ('Etm', '*Az emberi test működése');
INSERT INTO `targyak` VALUES ('Ebab', '*Az emésztőrendszer betegségei anyagcsere betegségek');
INSERT INTO `targyak` VALUES ('Iego', '*Az idős emberek gondozásának gyakorlata');
INSERT INTO `targyak` VALUES ('Igts', '*Az idősgondozás tervezése sajátosságai');
INSERT INTO `targyak` VALUES ('Iekd', '*Az intézmény ellenőrzésével kapcsolatos dokumentumok');
INSERT INTO `targyak` VALUES ('Imkd', '*Az intézmény működésével kapcsolatos dokumentumok');
INSERT INTO `targyak` VALUES ('Igt', '*Az intézményi gazdálkodás tervezése');
INSERT INTO `targyak` VALUES ('Bv', '*Balesetvédelem');
INSERT INTO `targyak` VALUES ('Bea', '*Beavatkozások');
INSERT INTO `targyak` VALUES ('Bel', '*Belgyógyászat ');
INSERT INTO `targyak` VALUES ('Belko', '*Belgyógyászati / krónikus /osztályon');
INSERT INTO `targyak` VALUES ('Belo', '*Belgyógyászati osztályon ');
INSERT INTO `targyak` VALUES ('Bak', '*Betegbiztonság ,ápolási kockázatok');
INSERT INTO `targyak` VALUES ('Bszk', '*Betegszállítás,kísérés');
INSERT INTO `targyak` VALUES ('Biofi', '*Biofizika');
INSERT INTO `targyak` VALUES ('Bioke', '*Biokémia');
INSERT INTO `targyak` VALUES ('Csel', '*Család és életmód');
INSERT INTO `targyak` VALUES ('Css', '*Családsegítés');
INSERT INTO `targyak` VALUES ('Cssr', '*Családsegítés részfeladatai');
INSERT INTO `targyak` VALUES ('Csgyo', '*Csecsemő és gyermek osztályon');
INSERT INTO `targyak` VALUES ('Csszm', '*Csoportokkal végzett szociális munka gyakorlata');
INSERT INTO `targyak` VALUES ('Demo', '*Demostrációs termi gyak. /Megfigyelés észlelésből');
INSERT INTO `targyak` VALUES ('Diag', '*Diagnosztika');
INSERT INTO `targyak` VALUES ('Diai', '*Diagnosztikai ismeretek');
INSERT INTO `targyak` VALUES ('Diet', '*Dietetika');
INSERT INTO `targyak` VALUES ('Dieti', '*Dietetikai ismeretek');
INSERT INTO `targyak` VALUES ('Egb', '*Egészség betegség');
INSERT INTO `targyak` VALUES ('Eta', '*Egészséges táplálkozás');
INSERT INTO `targyak` VALUES ('Egf', '*Egészségfejlesztés');
INSERT INTO `targyak` VALUES ('Ege', '*Egészséggondozás elm.');
INSERT INTO `targyak` VALUES ('Egy', '*Egészséggondozás gyak.');
INSERT INTO `targyak` VALUES ('Egor', '*Egészségmegőrzés');
INSERT INTO `targyak` VALUES ('Egn', '*Egészségnevelés');
INSERT INTO `targyak` VALUES ('Egp', '*Egészségpedagógia');
INSERT INTO `targyak` VALUES ('Emk', '*Egészségtudatos magatartás kialakítása');
INSERT INTO `targyak` VALUES ('Ecssz', '*Egyének és családok szükségleteti');
INSERT INTO `targyak` VALUES ('Eek', '*Egyéni esetkezelés');
INSERT INTO `targyak` VALUES ('Eesr', '*Egyéni esetkezelés részfeladatai');
INSERT INTO `targyak` VALUES ('Emv', '*Életmódváltás');
INSERT INTO `targyak` VALUES ('Epsz', '*Életút pszichológia');
INSERT INTO `targyak` VALUES ('Ea', '*Elkülönített alapok');
INSERT INTO `targyak` VALUES ('Esnye', '*Első segítség nyújtás alapismeretei elm.');
INSERT INTO `targyak` VALUES ('Esgy', '*Első segítség nyújtás gyakorlata');
INSERT INTO `targyak` VALUES ('Eszgy', '*Elsősegély nyújtási  szakmai gyakorlatok');
INSERT INTO `targyak` VALUES ('.Enyai', '*Elsősegély nyújtási alapismeretek gyak.');
INSERT INTO `targyak` VALUES ('Esny', '*Elsősegélynyújtás');
INSERT INTO `targyak` VALUES ('Esnyd', '*Elsősegélynyújtás /demons');
INSERT INTO `targyak` VALUES ('.Eny', '*Elsősegélynyújtás gyakorlata');
INSERT INTO `targyak` VALUES ('Esnyi', '*Elsősegélynyújtási ismeretek');
INSERT INTO `targyak` VALUES ('Efkf', '*Eltérő fejlődés, korai fejlesztés');
INSERT INTO `targyak` VALUES ('Ebdm', '*Endokrin betegségek daganatos megbetegedések');
INSERT INTO `targyak` VALUES ('Eszi', '*Érdekérvényesítés a szociális intézményekben');
INSERT INTO `targyak` VALUES ('Ecsgy', '*Esetkezelés és családsegítés gyakorlata');
INSERT INTO `targyak` VALUES ('Esmb', '*Esetmegbeszélés');
INSERT INTO `targyak` VALUES ('Eti', '*Etika');
INSERT INTO `targyak` VALUES ('Etsz', '*Etikai szabályok');
INSERT INTO `targyak` VALUES ('Etjk', '*Etikus jogszerű kommunikáció');
INSERT INTO `targyak` VALUES ('Fszla', '*Fejlődés - és személyiség - lélektani alapismeretek');
INSERT INTO `targyak` VALUES ('Frf', '*Fejlődési rendellenességek, fogyatékosságok');
INSERT INTO `targyak` VALUES ('Fer', '*Fertőtlenítés, sterilizálás');
INSERT INTO `targyak` VALUES ('Feloz', '*Fertőzések megelőzése');
INSERT INTO `targyak` VALUES ('Fgy', '*Foglalkozási gyakorlat');
INSERT INTO `targyak` VALUES ('Freh', '*Fogyatékosságok és rehabilitációjuk');
INSERT INTO `targyak` VALUES ('Fogo', '*Fül -orr-gégészeti osztályon');
INSERT INTO `targyak` VALUES ('Geri', '*Geriátria');
INSERT INTO `targyak` VALUES ('Girl', '*Gerontológia és az idősek rehabilitációjának lehetőségei');
INSERT INTO `targyak` VALUES ('Gon', '*Gondozás');
INSERT INTO `targyak` VALUES ('.Go', '*Gondozási gyakorlat');
INSERT INTO `targyak` VALUES ('Goi', '*Gondozási ismeretek');
INSERT INTO `targyak` VALUES ('.Goi', '*Gondozási ismeretek gyak.');
INSERT INTO `targyak` VALUES (';Gyak', '*Gyakorlat');
INSERT INTO `targyak` VALUES ('Gycs', '*Gyakorlat a család és életmód körében');
INSERT INTO `targyak` VALUES ('Gyb', '*Gyermekbetegségek');
INSERT INTO `targyak` VALUES ('Gyny', '*Gyermekellátási gyakorlat nyári összefüggő');
INSERT INTO `targyak` VALUES ('.Gyagy', '*Gyermekgondozási, ápolási gyakorlat demons');
INSERT INTO `targyak` VALUES ('Gygy', '*Gyermekgyógyászat');
INSERT INTO `targyak` VALUES ('Gyevn', '*Gyermekirodalom, ének, zene, vizuális nevelés');
INSERT INTO `targyak` VALUES ('Gyod', '*Gyermekotthoni dokumentáció');
INSERT INTO `targyak` VALUES ('Gyogy', '*Gyermekotthoni gyakorlat');
INSERT INTO `targyak` VALUES ('Gyvj', '*Gyermekvédelmi jogok');
INSERT INTO `targyak` VALUES ('Gysz', '*Gyógyszerelés');
INSERT INTO `targyak` VALUES ('.Gysz', '*Gyógyszerelési gyakorlat');
INSERT INTO `targyak` VALUES ('Gyszt', '*Gyógyszertan');
INSERT INTO `targyak` VALUES ('Hael', '*Haldoklók és elhunytak');
INSERT INTO `targyak` VALUES ('.Htgy', '*Háztartási gyakorlat');
INSERT INTO `targyak` VALUES ('Hti', '*Háztartási ismeretek');
INSERT INTO `targyak` VALUES ('Hfi', '*Higiénés és fertőtlenítési ismeretek');
INSERT INTO `targyak` VALUES ('Hos', '*Hospice');
INSERT INTO `targyak` VALUES ('Iea', '*Ideg- és elmegyógyászati alapok');
INSERT INTO `targyak` VALUES ('Inti', '*Intézmény megismerése');
INSERT INTO `targyak` VALUES ('Jtan', '*Járványtan');
INSERT INTO `targyak` VALUES ('Jtmb', '*Járványtan-mikrobiológia');
INSERT INTO `targyak` VALUES ('Jog', '*Jogi alapismeretek');
INSERT INTO `targyak` VALUES ('Jei', '*Jogi és etikai ismeretek ');
INSERT INTO `targyak` VALUES ('Ji', '*Jogi ismeretek ');
INSERT INTO `targyak` VALUES ('Jsz', '*Jogi szabályok');
INSERT INTO `targyak` VALUES ('Kskm', '*Készségf. a segítő kapcsolat működtetéséhez');
INSERT INTO `targyak` VALUES ('Kef', '*Készségfejlesztés');
INSERT INTO `targyak` VALUES ('Kfsk', '*Készségfejlesztés a segítő kapcsolat működtetéséhez');
INSERT INTO `targyak` VALUES ('Klgy', '*Klinikai gyakorlat');
INSERT INTO `targyak` VALUES ('Kltgy', '*Klinikai területi gyakorlatok ');
INSERT INTO `targyak` VALUES ('Kbm', '*Kommunikáció a beteggel, munkatársakkal');
INSERT INTO `targyak` VALUES ('Kesz', '*Kommunikáció az egészségügyi szolgálatban');
INSERT INTO `targyak` VALUES ('Kszk', '*Kommunikáció, szakmai kommunikáció');
INSERT INTO `targyak` VALUES ('Kk', '*Kórok és kórokozók');
INSERT INTO `targyak` VALUES ('Kdi', '*Kórtani-diagnosztikai ismeretek');
INSERT INTO `targyak` VALUES ('Ktgy', '*Kölcsönös tájékozódás a gyermekről');
INSERT INTO `targyak` VALUES ('Kvai', '*Költségvetési alapismeretek');
INSERT INTO `targyak` VALUES ('Keg', '*Közegészség');
INSERT INTO `targyak` VALUES ('Kegt', '*Közegészségtan');
INSERT INTO `targyak` VALUES ('Kga', '*Közgazdasági alapismeretek');
INSERT INTO `targyak` VALUES ('Kii', '*Közigazgatási ismeretek');
INSERT INTO `targyak` VALUES ('Kszm', '*Közösségi szociális munka');
INSERT INTO `targyak` VALUES ('Kszmg', '*Közösségi szociális munka gyakorlata');
INSERT INTO `targyak` VALUES ('Lat', '*Latin nyelv');
INSERT INTO `targyak` VALUES ('Le', '*Lelki egészség');
INSERT INTO `targyak` VALUES ('Lev', '*Lelki egészségvédelem');
INSERT INTO `targyak` VALUES ('Lbg', '*Létszám és bérgazdálkodás');
INSERT INTO `targyak` VALUES ('Mny', '*Magyar nyelv ');
INSERT INTO `targyak` VALUES ('Mmt', '*Mai magyar társadalom');
INSERT INTO `targyak` VALUES ('Mff', '*Megfigyelési feladatok');
INSERT INTO `targyak` VALUES ('Mm', '*Menedzsment');
INSERT INTO `targyak` VALUES ('Meal', '*Mentálhigiéné-ápolás lélektan ');
INSERT INTO `targyak` VALUES ('Mbt', '*Munka- baleset- és tűzvédelem');
INSERT INTO `targyak` VALUES ('Mbtgy', '*Munka- baleset- és tűzvédelemi gyakorlat');
INSERT INTO `targyak` VALUES ('Mvtu', '*Munkavédelem-tűzvédelem');
INSERT INTO `targyak` VALUES ('Nevp', '*Nevelési ismeretek / pszichológia');
INSERT INTO `targyak` VALUES ('Nszb', '*Normák szabályok betartása');
INSERT INTO `targyak` VALUES ('Nof', '*Nosocomiális fertőzések');
INSERT INTO `targyak` VALUES ('Olat', '*Orvosi latin');
INSERT INTO `targyak` VALUES ('Oasz', '*Otthoni ápolási szolgálatnál');
INSERT INTO `targyak` VALUES ('Psz', '*Pedagógia - szociológia');
INSERT INTO `targyak` VALUES ('Pai', '*Pedagógiai alapismeretek');
INSERT INTO `targyak` VALUES ('Pfe', '*Pedagógiai feladatok ellátása');
INSERT INTO `targyak` VALUES ('Pdo', '*Probléma definiálásnak összefügg.');
INSERT INTO `targyak` VALUES ('Pfgy', '*Problémák feltárásának gyakorlata');
INSERT INTO `targyak` VALUES ('Pfm', '*Problémák feltárásának módszerei');
INSERT INTO `targyak` VALUES ('Pszo', '*Pszichiátriai osztályon');
INSERT INTO `targyak` VALUES ('Pszni', '*Pszichológiai alapismeretek, nevelési ism.');
INSERT INTO `targyak` VALUES ('Pim', '*Pszichológiai ismeretszerzés módszerei');
INSERT INTO `targyak` VALUES ('Rea', '*Reumatológiai alapismeretek');
INSERT INTO `targyak` VALUES ('Sm', '*Sebek és műtétek');
INSERT INTO `targyak` VALUES ('Seb', '*Sebészet');
INSERT INTO `targyak` VALUES ('Seib', '*Sebészeti ellátást igénylő betegségek');
INSERT INTO `targyak` VALUES ('Sebo', '*Sebészeti osztályon');
INSERT INTO `targyak` VALUES ('Skk', '*Segítő kapcsolat kommunikációja');
INSERT INTO `targyak` VALUES ('So', '*Sérülések osztályozása');
INSERT INTO `targyak` VALUES ('Szaf', '*Szabadidő fontossága');
INSERT INTO `targyak` VALUES ('Szeti', '*Szakmai etika');
INSERT INTO `targyak` VALUES ('Szszf', '*Szakmai személyiségfejlesztés');
INSERT INTO `targyak` VALUES ('Sztgy', '*Számítástechnikai gyakorlat');
INSERT INTO `targyak` VALUES ('Szti', '*Számítástechnikai ismeretek');
INSERT INTO `targyak` VALUES ('Szpsz', '*Személyiség pszichológia');
INSERT INTO `targyak` VALUES ('Szr', '*Szenvedélybetegségek és rehabilitáció');
INSERT INTO `targyak` VALUES ('Szemu', '*Szervezet működését károsító állapotok');
INSERT INTO `targyak` VALUES ('Szszo', '*Szervezetszociológia');
INSERT INTO `targyak` VALUES ('Szoai', '*Szervezetszociológiai alapismeretek');
INSERT INTO `targyak` VALUES ('Szelf', '*Szociális ellátás finanszírozása');
INSERT INTO `targyak` VALUES ('Szm', '*Szociális munka');
INSERT INTO `targyak` VALUES ('Szmcs', '*Szociális munka csoportokkal');
INSERT INTO `targyak` VALUES ('Szmtk', '*Szociális munka társadalmi közege');
INSERT INTO `targyak` VALUES ('Szpms', '*Szociális problémák megoldásának sajátosságai');
INSERT INTO `targyak` VALUES ('Szpt', '*Szociális problémák tudatosítása');
INSERT INTO `targyak` VALUES ('Szpm', '*Szociális problémamgeoldás');
INSERT INTO `targyak` VALUES ('Szoc', '*Szocializáció');
INSERT INTO `targyak` VALUES ('Szoco', '*Szocializációs összefüggések');
INSERT INTO `targyak` VALUES ('Szpint', '*Szociálpolitika intézményrendszere');
INSERT INTO `targyak` VALUES ('Szpi', '*Szociálpolitikai alapismeretek');
INSERT INTO `targyak` VALUES ('Szpa', '*Szociálpolitikai alapok');
INSERT INTO `targyak` VALUES ('Szpbip', '*Szociálpolitikai beavatkozást igénylő problémák');
INSERT INTO `targyak` VALUES ('Szpmo', '*Szociálpolitikai monitorozás / Monitorozó');
INSERT INTO `targyak` VALUES ('Szpszi', '*Szociálpszichológia');
INSERT INTO `targyak` VALUES ('Szpai', '*Szociálpszichológiai alapismeretek');
INSERT INTO `targyak` VALUES ('Szpjf', '*Szociálpszichológiai jelenségek és folyamatok');
INSERT INTO `targyak` VALUES ('Szoa', '*Szociológiai alapismeretek');
INSERT INTO `targyak` VALUES ('Szaigy', '*Szociológiai alapismeretek gyakorlat');
INSERT INTO `targyak` VALUES ('Szgy', '*Szociológiai gyakorlat');
INSERT INTO `targyak` VALUES ('Szvi', '*Szupervízió');
INSERT INTO `targyak` VALUES ('Szecs', '*Szükségletek és erőforrások a csoportban');
INSERT INTO `targyak` VALUES ('Szeke', '*Szükségletek és erőforrások komplex értelmezése');
INSERT INTO `targyak` VALUES ('Szfgy', '*Szükségletfelmérési gyakorlat');
INSERT INTO `targyak` VALUES ('Szek', '*Szükséletek és erőforrások a közösségben');
INSERT INTO `targyak` VALUES ('Szul', '*Szülészet-nőgyógyászati osztályon');
INSERT INTO `targyak` VALUES ('Tesz', '*Társadalmi egyenlőtlenség és szegénység');
INSERT INTO `targyak` VALUES ('Tstr', '*Társadalmi struktúra');
INSERT INTO `targyak` VALUES ('Tiko', '*Társadalomintegrációjával kapcsolatos összefüggések');
INSERT INTO `targyak` VALUES ('Tto', '*Társadalomtörténeti összefüggések');
INSERT INTO `targyak` VALUES ('Tke', '*Település és környezetegészségtan');
INSERT INTO `targyak` VALUES ('Tei', '*Terápiás ismeretek');
INSERT INTO `targyak` VALUES ('Tegy', '*Természetgyógyászat / alternatív terápiák');
INSERT INTO `targyak` VALUES ('Trau', '*Traumatológiai osztályon');
INSERT INTO `targyak` VALUES ('Tun', '*Tünetek észlelése/mérése-dokumentálása');
INSERT INTO `targyak` VALUES ('Urol', '*Urológia és a nemi szervek megbetegedései');
INSERT INTO `targyak` VALUES ('Vhmt', '*Veszélyes hulladékkezelés, munka és tűzvédelem');
INSERT INTO `targyak` VALUES ('Vszgy', '*Vezetési szervezési gyakorlat');
INSERT INTO `targyak` VALUES ('Szpv', 'A szociális pályák világa');
INSERT INTO `targyak` VALUES ('Alapszgyak', 'Alapszerkesztési gyakorlat');
INSERT INTO `targyak` VALUES ('aBio', 'Alkalmazott biológia');
INSERT INTO `targyak` VALUES ('aKe', 'Alkalmazott kémia');
INSERT INTO `targyak` VALUES ('Aai', 'Általános áruismeret');
INSERT INTO `targyak` VALUES ('Asz', 'Általános és személyiséglélektan');
INSERT INTO `targyak` VALUES ('Aji', 'Általános jogi ismeretek');
INSERT INTO `targyak` VALUES ('Ana', 'Anatómia');
INSERT INTO `targyak` VALUES ('Anata', 'Anatómia és élettan');
INSERT INTO `targyak` VALUES ('A', 'Angol nyelv');
INSERT INTO `targyak` VALUES ('Anygy', 'Anyag- és gyártásismeret');
INSERT INTO `targyak` VALUES ('Anyag', 'Anyagismeret');
INSERT INTO `targyak` VALUES ('Anyism I.', 'Anyagismeret I.');
INSERT INTO `targyak` VALUES ('Anyism II.', 'Anyagismeret II.');
INSERT INTO `targyak` VALUES ('Avizsg', 'Anyagvizsgálatok');
INSERT INTO `targyak` VALUES ('Ai', 'Áruforgalmi ismeretek');
INSERT INTO `targyak` VALUES ('Aany', 'Asztalos anyagismeret');
INSERT INTO `targyak` VALUES ('Aszg', 'Asztalos szakmai és gépismeret');
INSERT INTO `targyak` VALUES ('Aszr', 'Asztalos szerkezettan-szakrajz');
INSERT INTO `targyak` VALUES ('Epv', 'Az egészségügyi pályák világa');
INSERT INTO `targyak` VALUES ('Bri', 'Belügyi rendészeti ismeretek');
INSERT INTO `targyak` VALUES ('Bksz', 'Bevezetés a kereskedelem szervezezésébe');
INSERT INTO `targyak` VALUES ('Bkv', 'Bevezetés a kereskedelmi vállalkozások gazdálkodásába');
INSERT INTO `targyak` VALUES ('Bepsz', 'Bevezetés az építészeti szakmai számításokba');
INSERT INTO `targyak` VALUES ('Bio', 'Biológia');
INSERT INTO `targyak` VALUES ('Bio_v', 'Biológia választott');
INSERT INTO `targyak` VALUES ('Be', 'Burkolás előkészítése');
INSERT INTO `targyak` VALUES ('CNC_f', 'CNC forgácsolás');
INSERT INTO `targyak` VALUES ('CNC_i', 'CNC ismeretek');
INSERT INTO `targyak` VALUES ('Cuism', 'Cukrász ismeret');
INSERT INTO `targyak` VALUES ('Edz', 'Edzés');
INSERT INTO `targyak` VALUES ('Egg', 'Egészséggondozás');
INSERT INTO `targyak` VALUES ('Egt', 'Egészségtan');
INSERT INTO `targyak` VALUES ('Ef', 'Egyéni foglalkozás');
INSERT INTO `targyak` VALUES ('Ek', 'Elektrokozmetika');
INSERT INTO `targyak` VALUES ('EeváI', 'Élelmiszer és vegyiáruk áruismerete I.');
INSERT INTO `targyak` VALUES ('Elelmism', 'Élelmiszer ismeret');
INSERT INTO `targyak` VALUES ('Evau', 'Élelmiszer- és vegyiáru áruismeret');
INSERT INTO `targyak` VALUES ('El', 'Életmód');
INSERT INTO `targyak` VALUES ('Et', 'Emberi test');
INSERT INTO `targyak` VALUES ('En', 'Ének-zene');
INSERT INTO `targyak` VALUES ('Eai', 'Építészeti alapismeretek');
INSERT INTO `targyak` VALUES ('Emr', 'Építészeti műszaki rajz');
INSERT INTO `targyak` VALUES ('Epa', 'Építőanyagok');
INSERT INTO `targyak` VALUES ('Ep.alapism', 'Építőipari alapismeretek');
INSERT INTO `targyak` VALUES ('Epat', 'Építőipari alaptevékenységek');
INSERT INTO `targyak` VALUES ('Epg', 'Építőipari gépek');
INSERT INTO `targyak` VALUES ('Eszagy', 'Építőipari szakmai alapozó gyakorlat');
INSERT INTO `targyak` VALUES ('Epany', 'Épületburkoló anyagismeret');
INSERT INTO `targyak` VALUES ('Epszi', 'Épületburkoló szakmai ismeretek');
INSERT INTO `targyak` VALUES ('Ebszr', 'Épületburkoló szakrajz');
INSERT INTO `targyak` VALUES ('Epd', 'Épületdiagnosztika');
INSERT INTO `targyak` VALUES ('Eff', 'Érettségire felkészítő foglalkozás');
INSERT INTO `targyak` VALUES ('Eszterg', 'Esztergálás');
INSERT INTO `targyak` VALUES ('Etitkeszism', 'Étel és ital készítési ismeret');
INSERT INTO `targyak` VALUES ('Etkeszism', 'Ételkészítési ismeret');
INSERT INTO `targyak` VALUES ('Etk', 'Etika és kommunikáció');
INSERT INTO `targyak` VALUES ('.Etk', 'Etika és kommunikáció (egy)');
INSERT INTO `targyak` VALUES ('Fany', 'Faipari anyagismeret');
INSERT INTO `targyak` VALUES ('Fagy', 'Faipari szakmai alapozó gyakorlat');
INSERT INTO `targyak` VALUES ('Fszai', 'Faipari szakmai alapozó ismeretek');
INSERT INTO `targyak` VALUES ('Fagep', 'Fapari gépek');
INSERT INTO `targyak` VALUES ('Fsz', 'Fejlődéslélektan és szocializáció');
INSERT INTO `targyak` VALUES ('Fef', 'Fenntartás és felújítás');
INSERT INTO `targyak` VALUES ('fefetech', 'Fenntartás és felújítási tech.');
INSERT INTO `targyak` VALUES ('Fft', 'Fenntartásépítési és felújítási technológiák');
INSERT INTO `targyak` VALUES ('Fi', 'Fizika');
INSERT INTO `targyak` VALUES ('Ff', 'Fizikális felkészítés');
INSERT INTO `targyak` VALUES ('Fai', 'Fodrász anyagismeret');
INSERT INTO `targyak` VALUES ('FoGy', 'Fodrász gyakorlat');
INSERT INTO `targyak` VALUES ('Forajzvizkul', 'Fodrász rajz és vizuális kultúra');
INSERT INTO `targyak` VALUES ('Fszagy', 'Fodrász szakmai alapozó gyakorlat');
INSERT INTO `targyak` VALUES ('Foszi', 'Fodrász szakmai ismeretek');
INSERT INTO `targyak` VALUES ('.Foszi', 'Fodrász szakmai ismeretek (egy)');
INSERT INTO `targyak` VALUES ('Fo', 'Földünk és környezetünk ');
INSERT INTO `targyak` VALUES ('Fo_v', 'Földünk és környezetünk választott');
INSERT INTO `targyak` VALUES ('Fr', 'Fuvarozás és raktárlogisztika');
INSERT INTO `targyak` VALUES ('Gasz', 'Gasztronómiai alapismeretek');
INSERT INTO `targyak` VALUES ('Gazdi', 'Gazdálkodási ismeretek');
INSERT INTO `targyak` VALUES ('Gi', 'Gazdálkodási ismeretek');
INSERT INTO `targyak` VALUES ('Gai', 'Gazdasági alapismeretek');
INSERT INTO `targyak` VALUES ('Gko', 'Gazdasági környezetünk');
INSERT INTO `targyak` VALUES ('Gmai', 'Gazdasági- és munkajogi alapismeretek');
INSERT INTO `targyak` VALUES ('Gmi', 'Gazdasági, munkajogi ismeretek');
INSERT INTO `targyak` VALUES ('Gevi', 'Gazdsági és vállalkozási ismeretk');
INSERT INTO `targyak` VALUES ('Geomm', 'Geometriai mérések');
INSERT INTO `targyak` VALUES ('Gszagy', 'Gépészeti szakmai alapozó gyakorlat');
INSERT INTO `targyak` VALUES ('Gforg', 'Gépi forgácsolás');
INSERT INTO `targyak` VALUES ('Gtech', 'Gépi technológiák');
INSERT INTO `targyak` VALUES ('Gepi', 'Gépírás, szövegszerkesztés');
INSERT INTO `targyak` VALUES ('Gepjdiag', 'Gépjármű diagnosztika');
INSERT INTO `targyak` VALUES ('Geszt', 'Gépjármű-szerkezettan');
INSERT INTO `targyak` VALUES ('Gev', 'Gépjármű-villamosságtan');
INSERT INTO `targyak` VALUES ('G', 'Géptan');
INSERT INTO `targyak` VALUES ('Gt', 'Gondozástan');
INSERT INTO `targyak` VALUES ('Gyak', 'Gyakorlati oktatás');
INSERT INTO `targyak` VALUES ('GyarBefDok', 'Gyártás befejezés, dokumentálás');
INSERT INTO `targyak` VALUES ('Gyeba', 'Gyártás előkészítés- befejezés alapmérés');
INSERT INTO `targyak` VALUES ('Gea', 'Gyártás és anyagismeret');
INSERT INTO `targyak` VALUES ('Ik', 'Információkezelés');
INSERT INTO `targyak` VALUES ('Inf', 'Informatika');
INSERT INTO `targyak` VALUES ('Inf2', 'Informatika II');
INSERT INTO `targyak` VALUES ('Inf_v', 'Informatika választott');
INSERT INTO `targyak` VALUES ('Infé', 'Informatika választott érettségi tantárgy');
INSERT INTO `targyak` VALUES ('Iag', 'Informatikai alaptev, gyak.');
INSERT INTO `targyak` VALUES ('Irtech', 'Irányítástechnika');
INSERT INTO `targyak` VALUES ('Italism', 'Ital ismeret');
INSERT INTO `targyak` VALUES ('Jvism', 'Jogi és vállalkozási ismeretek');
INSERT INTO `targyak` VALUES ('Joalk', 'Jogszabályok alkalmazás I-II.');
INSERT INTO `targyak` VALUES ('Ke', 'Kémia');
INSERT INTO `targyak` VALUES ('Kfod', 'Kémia (fodrász)');
INSERT INTO `targyak` VALUES ('Ke_v', 'Kémia választott');
INSERT INTO `targyak` VALUES ('Kai', 'Kereskedelem általános ismeretei');
INSERT INTO `targyak` VALUES ('Ksz', 'Kereskedelem szervezés');
INSERT INTO `targyak` VALUES ('Keszagy', 'Kereskedelmi szakmai alapozó gyakorlat');
INSERT INTO `targyak` VALUES ('Kvg', 'Kereskedelmi vállalatok gazdálkodása');
INSERT INTO `targyak` VALUES ('Kom', 'Kommunikáció');
INSERT INTO `targyak` VALUES ('Kommalt', 'Kommunikáció ált.');
INSERT INTO `targyak` VALUES ('KaA', 'Kommunikáció idegen nyelven (Angol)');
INSERT INTO `targyak` VALUES ('KoN', 'Kommunikáció idegen nyelven (Német)');
INSERT INTO `targyak` VALUES ('Kgy', 'Kommunikációs gyakorlat');
INSERT INTO `targyak` VALUES ('Koai', 'Kozmetikus anyagismeret');
INSERT INTO `targyak` VALUES ('.KoGY', 'Kozmetikus laboratóriumi gyakorlat (egy)');
INSERT INTO `targyak` VALUES ('Kosziok', 'Kozmetikus szakmai ismeret');
INSERT INTO `targyak` VALUES ('Koszik', 'Kozmetikus szakmai ismeret kozmetikusi');
INSERT INTO `targyak` VALUES ('Koszio', 'Kozmetikus szakmai ismeret orvosi');
INSERT INTO `targyak` VALUES ('Kv', 'Környezetvédelem');
INSERT INTO `targyak` VALUES ('.Kv', 'Környezetvédelem (egy)');
INSERT INTO `targyak` VALUES ('Kg', 'Közgazdaságtan');
INSERT INTO `targyak` VALUES ('Kf', 'Közlekedési földrajz');
INSERT INTO `targyak` VALUES ('Kinf', 'Közlekedési informatika és számtech gyakorlat');
INSERT INTO `targyak` VALUES ('Ki', 'Közlekedési ismeretek');
INSERT INTO `targyak` VALUES ('Kszgy', 'Kreatív színházi gyakorlat');
INSERT INTO `targyak` VALUES ('Kki', 'Külkereskedelmi ismeretek');
INSERT INTO `targyak` VALUES (';kgyak', 'külső gyak');
INSERT INTO `targyak` VALUES (';kulgyak', 'Külső gyakorlat');
INSERT INTO `targyak` VALUES ('Loha', 'Lóhasználat');
INSERT INTO `targyak` VALUES ('Lote', 'Lótenyésztés');
INSERT INTO `targyak` VALUES ('Loeg', 'Lovak egészségvédelme');
INSERT INTO `targyak` VALUES ('I', 'Magyar irodalom');
INSERT INTO `targyak` VALUES ('Ny', 'Magyar nyelv');
INSERT INTO `targyak` VALUES ('Magy', 'Magyar nyelv és irodalom');
INSERT INTO `targyak` VALUES ('Mar', 'Marketing');
INSERT INTO `targyak` VALUES ('Mai', 'Marketing alapismeretek');
INSERT INTO `targyak` VALUES ('Maralapism', 'Marketing alapismeretek');
INSERT INTO `targyak` VALUES ('Mk', 'Marketing kommunikáció');
INSERT INTO `targyak` VALUES ('Makovallgy', 'Marketing, kommunikáció és vállalkozási gyakorlat');
INSERT INTO `targyak` VALUES ('Mat', 'Matematika');
INSERT INTO `targyak` VALUES ('Mech', 'Mechanika');
INSERT INTO `targyak` VALUES ('Melviz', 'Melegvíz ellőállítás');
INSERT INTO `targyak` VALUES ('Me', 'Mentálhigiéné');
INSERT INTO `targyak` VALUES ('Meany', 'Mérések, anyagok');
INSERT INTO `targyak` VALUES ('Mt', 'Méréstechnika');
INSERT INTO `targyak` VALUES ('Mi', 'Mindennapi ismeretek');
INSERT INTO `targyak` VALUES ('Mhae', 'Minőségbiztosítás higénia az élelmiszeriparban');
INSERT INTO `targyak` VALUES ('Mkv', 'Munka- és környezetvédelem');
INSERT INTO `targyak` VALUES ('mkv_sz', 'Munka- és környezetvédelem (szakmai)');
INSERT INTO `targyak` VALUES ('Mbtkved', 'Munka-, baleset-, tűz- és környezetvédelem');
INSERT INTO `targyak` VALUES ('Mke_ved', 'Munka-, környezet- és egészségvédelem');
INSERT INTO `targyak` VALUES ('Mtkv', 'Munka-, tűz és környezetvédelem');
INSERT INTO `targyak` VALUES ('Munkszerv', 'Munkaszervezés (Vállalkozási ism.)');
INSERT INTO `targyak` VALUES ('Mv', 'Munkavédelem');
INSERT INTO `targyak` VALUES ('.Mv', 'Munkavédelem (egy)');
INSERT INTO `targyak` VALUES ('Muemlv', 'Műemlékvédelem');
INSERT INTO `targyak` VALUES ('Mabr', 'Műszaki ábrázolás');
INSERT INTO `targyak` VALUES ('Mu', 'Műszaki ábrázolás alapjai (fég)');
INSERT INTO `targyak` VALUES ('Mua', 'Műszaki alapismeretek');
INSERT INTO `targyak` VALUES ('Muai', 'Műszaki áruismeret');
INSERT INTO `targyak` VALUES ('Mudok', 'Műszaki dokumentációk');
INSERT INTO `targyak` VALUES ('Muea', 'Műszaki és építészeti alapismeretek');
INSERT INTO `targyak` VALUES ('M_inf', 'Műszaki informatika');
INSERT INTO `targyak` VALUES ('Muism', 'Műszaki ismeretek');
INSERT INTO `targyak` VALUES ('Mum', 'Műszaki mérések');
INSERT INTO `targyak` VALUES ('Mur', 'Műszaki rajz');
INSERT INTO `targyak` VALUES ('Mipmt', 'Művészet és iparművészet története');
INSERT INTO `targyak` VALUES ('N', 'Német nyelv');
INSERT INTO `targyak` VALUES ('Nusz', 'Nemzetközi ügyletek szervezése');
INSERT INTO `targyak` VALUES ('Neprajz', 'Néprajz');
INSERT INTO `targyak` VALUES ('Of', 'Osztályfőnöki');
INSERT INTO `targyak` VALUES ('Oti', 'Ön- és társismeret');
INSERT INTO `targyak` VALUES ('Oai', 'Önvédelmi alapismeret');
INSERT INTO `targyak` VALUES ('Pv', 'Pályák világa');
INSERT INTO `targyak` VALUES ('Pv_d', 'Pályák világa (drámaforgó)');
INSERT INTO `targyak` VALUES ('Pv_k', 'Pályák világa (kerforgó)');
INSERT INTO `targyak` VALUES ('Pv_r', 'Pályák világa (rendforgó)');
INSERT INTO `targyak` VALUES ('Pv_sze', 'Pályák világa (szépforgó)');
INSERT INTO `targyak` VALUES ('Pv_szo', 'Pályák világa (szocforgó)');
INSERT INTO `targyak` VALUES ('Pv_v', 'Pályák világa (vendforgó)');
INSERT INTO `targyak` VALUES ('Pv_e', 'Pályák világa(eüforgó)');
INSERT INTO `targyak` VALUES ('Pv_m', 'Pályák világa(műszforgó)');
INSERT INTO `targyak` VALUES ('Po', 'Pályaorientáció');
INSERT INTO `targyak` VALUES ('Pt', 'Pék technológia');
INSERT INTO `targyak` VALUES ('PNYR', 'Pénzforgalmi és nyilvántartási rendszerek');
INSERT INTO `targyak` VALUES ('Pkgy', 'Pénztárgép kezelése gyakorlat');
INSERT INTO `targyak` VALUES ('Pi', 'Piackutatás');
INSERT INTO `targyak` VALUES ('Pincism', 'Pincér ismeretek');
INSERT INTO `targyak` VALUES ('Pszagy', 'Pincér szakmai alapozó gyakorlat');
INSERT INTO `targyak` VALUES ('Pro', 'Projekt');
INSERT INTO `targyak` VALUES ('Pszi', 'Pszichológiai alapismeretek');
INSERT INTO `targyak` VALUES ('Ra', 'Rajz és vizuális kultúra');
INSERT INTO `targyak` VALUES ('Rpv', 'Rendészeti pályák világa');
INSERT INTO `targyak` VALUES ('Rany', 'Ruhaipari anyag- és áruismeret');
INSERT INTO `targyak` VALUES ('Rgept', 'Ruhaipari géptan');
INSERT INTO `targyak` VALUES ('Rtech', 'Ruhaipari technológia');
INSERT INTO `targyak` VALUES ('Ruai', 'Ruházati árúismeret');
INSERT INTO `targyak` VALUES ('Rtai', 'Ruházati termékek áruismerete I.');
INSERT INTO `targyak` VALUES ('Sti', 'Speciális társadalomismeret');
INSERT INTO `targyak` VALUES ('Szaszr', 'Szabás-szakrajz');
INSERT INTO `targyak` VALUES ('Szalapi', 'Szakmai alapismeret');
INSERT INTO `targyak` VALUES ('Szakai', 'Szakmai alapismeretek');
INSERT INTO `targyak` VALUES ('Sz.elm.', 'Szakmai elmélet');
INSERT INTO `targyak` VALUES ('Szeszt', 'Szakmai esztétika');
INSERT INTO `targyak` VALUES ('Szeszt_ra', 'Szakmai esztétika (Rajz)');
INSERT INTO `targyak` VALUES (';szgyakok', 'Szakmai gyakorlatok');
INSERT INTO `targyak` VALUES ('A_sz', 'Szakmai idegennyelv (Angol)');
INSERT INTO `targyak` VALUES ('N_sz', 'Szakmai idegennyelv (Német)');
INSERT INTO `targyak` VALUES ('SzInfo', 'Szakmai Informatika');
INSERT INTO `targyak` VALUES ('Szik', 'Szakmai ismeret');
INSERT INTO `targyak` VALUES ('Szism I', 'Szakmai ismeret I.');
INSERT INTO `targyak` VALUES ('Szism II', 'Szakmai ismeret II.');
INSERT INTO `targyak` VALUES ('Szi', 'Szakmai ismeretek');
INSERT INTO `targyak` VALUES ('Szi1', 'Szakmai ismeretek I.');
INSERT INTO `targyak` VALUES ('Szkom', 'Szakmai kommunikáció');
INSERT INTO `targyak` VALUES ('Szkm', 'Szakmai kommunikáció és mentálhigiéné');
INSERT INTO `targyak` VALUES ('Szsz', 'Szakmai számítás');
INSERT INTO `targyak` VALUES ('Szsz.', 'Szakmai számítás');
INSERT INTO `targyak` VALUES ('Szsz..', 'Szakmai számítások');
INSERT INTO `targyak` VALUES ('Szakra', 'Szakrajz');
INSERT INTO `targyak` VALUES ('Szakra2', 'Szakrajz II');
INSERT INTO `targyak` VALUES ('Szai', 'Szállodai ismeretek');
INSERT INTO `targyak` VALUES ('Sztech', 'Számítástechnika');
INSERT INTO `targyak` VALUES ('Szef', 'Személyiségfejlesztés');
INSERT INTO `targyak` VALUES ('Szelvez', 'Szennyvíz elvezetés');
INSERT INTO `targyak` VALUES ('Szh', 'Szépítészet és higiénia');
INSERT INTO `targyak` VALUES ('SzerkMod', 'Szerkesztés, modellezés');
INSERT INTO `targyak` VALUES ('Szmta', 'Szobafestő-mázoló és tapétázó anyagismeret');
INSERT INTO `targyak` VALUES ('Fszi', 'Szobafestő-mázoló és tapétázó szakmai ismeretek');
INSERT INTO `targyak` VALUES ('Szszr', 'Szobafestő-mázoló és tapétázó szakrajz');
INSERT INTO `targyak` VALUES ('Szp', 'Szociálpszichológia');
INSERT INTO `targyak` VALUES ('Tkt', 'Takarmányozástan');
INSERT INTO `targyak` VALUES ('Tgy', 'Tanirodai gyakorlat');
INSERT INTO `targyak` VALUES ('Tm', 'Tanulásmódszertan');
INSERT INTO `targyak` VALUES ('Tet', 'Tárgyalási és értékesítési technika');
INSERT INTO `targyak` VALUES ('Ti', 'Társadalmi ismeretek');
INSERT INTO `targyak` VALUES ('Tie', 'Társadalomismeret és etika');
INSERT INTO `targyak` VALUES ('Tisz', 'Társadalomismeret és szociálpolitika');
INSERT INTO `targyak` VALUES ('Te', 'Testnevelés és sport');
INSERT INTO `targyak` VALUES ('Te_v', 'Testnevelés és sport választott');
INSERT INTO `targyak` VALUES ('Tesé', 'Testnevelés választott érettségi tantárgy');
INSERT INTO `targyak` VALUES ('To', 'Történelem és állampolgári ismeretek');
INSERT INTO `targyak` VALUES ('Tor', 'Történelem és társadalomismeret');
INSERT INTO `targyak` VALUES ('Tuzmunkaved', 'Tűz- és munkavédelem');
INSERT INTO `targyak` VALUES ('Tuzrb', 'Tűzvédelmi rendszerek, berendezések');
INSERT INTO `targyak` VALUES ('Uep', 'Üzleti etika és protokoll');
INSERT INTO `targyak` VALUES ('Uk', 'Üzleti kommunikáció');
INSERT INTO `targyak` VALUES ('Ul', 'Üzleti lélektan');
INSERT INTO `targyak` VALUES ('Ulev', 'Üzleti levelezés');
INSERT INTO `targyak` VALUES ('Ust', 'Üzleti statisztika');
INSERT INTO `targyak` VALUES ('Uv', 'Üzleti vállalkozások');
INSERT INTO `targyak` VALUES ('Vgi', 'Vállalkozás és gazdasági ismeretek');
INSERT INTO `targyak` VALUES ('.Vgi', 'Vállalkozás és gazdasági ismeretek (egy)');
INSERT INTO `targyak` VALUES ('Vai', 'Vállalkozási alapismeretek');
INSERT INTO `targyak` VALUES ('Vji', 'Vállalkozási és jogi ismeretek');
INSERT INTO `targyak` VALUES ('Vallism', 'Vállalkozási ismeret');
INSERT INTO `targyak` VALUES ('Valli', 'Vállalkozási ismeretek');
INSERT INTO `targyak` VALUES ('Vi', 'Vállalkozási ismeretek');
INSERT INTO `targyak` VALUES ('Verm', 'Vállalkozások ellenőrzési rendszerei, módszere');
INSERT INTO `targyak` VALUES ('Vikr', 'Vállalkozások információs és kommunikációs rendszere');
INSERT INTO `targyak` VALUES ('Vsza', 'Vállalkozások számviteli alapjai');
INSERT INTO `targyak` VALUES ('Vengazvallis', 'Vend.gazd.váll.ism.');
INSERT INTO `targyak` VALUES ('Veai', 'Vendéglátás általános ismeretei');
INSERT INTO `targyak` VALUES ('Vti', 'Vendéglátó és turizmus ismeretek');
INSERT INTO `targyak` VALUES ('Vendgazdiism', 'Vendéglátó gazdasági ismeretek');
INSERT INTO `targyak` VALUES ('Vgy', 'Vendéglátó gyakorlat');
INSERT INTO `targyak` VALUES ('Veszagy', 'Vendéglátóipari szakmai alapozó gyakorlat');
INSERT INTO `targyak` VALUES ('VillBiztTech', 'Villamos biztonság technika');
INSERT INTO `targyak` VALUES ('VillDok', 'Villamos dokumentáció');
INSERT INTO `targyak` VALUES ('Vgbkadiag', 'Villamos gépek, berendezés, készülékek, áramkörök, diagnosztika');
INSERT INTO `targyak` VALUES ('VillHal', 'Villamos hálozatok');
INSERT INTO `targyak` VALUES ('VillKeszBer', 'Villamos készülék és berendezés');
INSERT INTO `targyak` VALUES ('Villszra', 'Villamos szakrajz alapismeretek');
INSERT INTO `targyak` VALUES ('Villszagy', 'Villamosipari szakmai alapozó gyakorlat');
INSERT INTO `targyak` VALUES ('Villa', 'Villamosságtani alapismeretek');
INSERT INTO `targyak` VALUES ('Vizell', 'Vízellátás');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
